// Placeholder for the ffigen output. The real file is generated by:
//
//   cd packages/photo_native
//   dart run ffigen --config ffigen.yaml
//
// CI fails if this placeholder remains after M2 (when bindings are first
// generated and committed). Keeping a stub here lets the rest of the Dart
// source tree typecheck during M1 without requiring everyone to run ffigen
// locally before the build pipeline is wired up.
//
// ignore_for_file: type=lint, non_constant_identifier_names

import 'dart:ffi' as ffi;

/// Placeholder. Generated bindings will replace this entire file.
class PhotoBindings {
  PhotoBindings(ffi.DynamicLibrary dylib) : _dylib = dylib;
  // ignore: unused_field
  final ffi.DynamicLibrary _dylib;

  static const int kPlaceholderRegenerateMe = 0;
}
