// GENERATED FILE — DO NOT EDIT.
// Regenerate with: `dart run ffigen --config ffigen.yaml`.
// ignore_for_file: type=lint, unused_field, camel_case_types,
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Generated Dart bindings for photo_core.h (the Pablo native ABI).
class PhotoBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PhotoBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PhotoBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Create an engine. Returns NULL on failure (config invalid, cache path not
  /// writable, catalog on a network FS, etc.). Each engine owns its own threads,
  /// cache, and catalog; multiple engines may coexist in one process but is not
  /// an expected use case.
  ///
  /// Thread-safety: not safe to call concurrently with itself for the same
  /// paths; safe across distinct paths.
  ffi.Pointer<photo_engine_t> photo_engine_create(
    ffi.Pointer<photo_config_t> cfg,
  ) {
    return _photo_engine_create(
      cfg,
    );
  }

  late final _photo_engine_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<photo_engine_t> Function(
              ffi.Pointer<photo_config_t>)>>('photo_engine_create');
  late final _photo_engine_create = _photo_engine_createPtr.asFunction<
      ffi.Pointer<photo_engine_t> Function(ffi.Pointer<photo_config_t>)>();

  /// Destroy an engine. Cancels in-flight work, flushes pending catalog writes,
  /// and closes the cache. Blocks until all workers exit. Safe to pass NULL.
  ///
  /// Thread-safety: must not be called while any other engine call is in flight.
  void photo_engine_destroy(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_engine_destroy(
      engine,
    );
  }

  late final _photo_engine_destroyPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_engine_destroy');
  late final _photo_engine_destroy = _photo_engine_destroyPtr
      .asFunction<void Function(ffi.Pointer<photo_engine_t>)>();

  /// Returns a static string. Format: "MAJOR.MINOR.PATCH+gitsha".
  ffi.Pointer<ffi.Char> photo_engine_version() {
    return _photo_engine_version();
  }

  late final _photo_engine_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'photo_engine_version');
  late final _photo_engine_version =
      _photo_engine_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// ABI version constant for runtime compatibility checks from Dart.
  int photo_abi_version() {
    return _photo_abi_version();
  }

  late final _photo_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('photo_abi_version');
  late final _photo_abi_version =
      _photo_abi_versionPtr.asFunction<int Function()>();

  /// ------------------------------------------------------------------------- */
  /// /* Slot lifecycle (called by the photo_native plugin, NOT by Dart)           */
  /// /*                                                                           */
  /// /* A slot is a logical render target. Each visible gallery tile has one      */
  /// /* slot for its lifetime. The plugin pairs each slot with a Flutter texture  */
  /// /* registration of equal lifetime. Stage upgrades swap frames within the     */
  /// /* slot; the Flutter texture ID never changes for the slot's life.           */
  /// /* -------------------------------------------------------------------------
  int photo_slot_create(
    ffi.Pointer<photo_engine_t> engine,
    int initial_w,
    int initial_h,
  ) {
    return _photo_slot_create(
      engine,
      initial_w,
      initial_h,
    );
  }

  late final _photo_slot_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>, ffi.Int32,
              ffi.Int32)>>('photo_slot_create');
  late final _photo_slot_create = _photo_slot_createPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  void photo_slot_destroy(
    ffi.Pointer<photo_engine_t> engine,
    int slot_id,
  ) {
    return _photo_slot_destroy(
      engine,
      slot_id,
    );
  }

  late final _photo_slot_destroyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<photo_engine_t>, ffi.Uint64)>>('photo_slot_destroy');
  late final _photo_slot_destroy = _photo_slot_destroyPtr
      .asFunction<void Function(ffi.Pointer<photo_engine_t>, int)>();

  /// Bind a generation token to a slot. Any in-flight request whose generation
  /// does not equal the slot's current generation will not produce a visible
  /// frame and will not emit STAGE_READY events. Used by the UI when a virtualized
  /// cell rebinds to a different asset.
  ///
  /// Thread-safety: callable from any thread. Returns previous generation.
  int photo_slot_bind_generation(
    ffi.Pointer<photo_engine_t> engine,
    int slot_id,
    int generation,
  ) {
    return _photo_slot_bind_generation(
      engine,
      slot_id,
      generation,
    );
  }

  late final _photo_slot_bind_generationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Uint64)>>('photo_slot_bind_generation');
  late final _photo_slot_bind_generation = _photo_slot_bind_generationPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  /// Hot path: submit a thumbnail request from Dart with zero heap allocation.
  /// The path_utf8 buffer must remain valid only for the duration of this call.
  ///
  /// Returns a non-zero request ID on success, 0 on rejection (invalid slot,
  /// empty path, etc.).
  ///
  /// Thread-safety: callable from any thread. Designed for p99 < 50 us on the
  /// Dart caller side.
  int photo_thumb_request_fast(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    int slot_id,
    int generation,
    ffi.Pointer<ffi.Char> path_utf8,
    int target_w,
    int target_h,
    int wanted_stages_mask,
    int priority,
    int flags,
  ) {
    return _photo_thumb_request_fast(
      engine,
      asset_id,
      slot_id,
      generation,
      path_utf8,
      target_w,
      target_h,
      wanted_stages_mask,
      priority,
      flags,
    );
  }

  late final _photo_thumb_request_fastPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Pointer<ffi.Char>,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Uint32)>>('photo_thumb_request_fast');
  late final _photo_thumb_request_fast =
      _photo_thumb_request_fastPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, int, int, int,
              ffi.Pointer<ffi.Char>, int, int, int, int, int)>();

  int photo_thumb_request(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_thumb_request_t> req,
  ) {
    return _photo_thumb_request(
      engine,
      req,
    );
  }

  late final _photo_thumb_requestPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_thumb_request_t>)>>('photo_thumb_request');
  late final _photo_thumb_request = _photo_thumb_requestPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_thumb_request_t>)>();

  /// Cancel a previously submitted thumbnail request. Cancellation is O(1) and
  /// advisory: in-flight work that has already produced a frame may still
  /// complete; the result will not be presented if the request's generation
  /// no longer matches the slot's current generation. Safe to call with an
  /// unknown ID.
  void photo_thumb_cancel(
    ffi.Pointer<photo_engine_t> engine,
    int request_id,
  ) {
    return _photo_thumb_cancel(
      engine,
      request_id,
    );
  }

  late final _photo_thumb_cancelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<photo_engine_t>, ffi.Uint64)>>('photo_thumb_cancel');
  late final _photo_thumb_cancel = _photo_thumb_cancelPtr
      .asFunction<void Function(ffi.Pointer<photo_engine_t>, int)>();

  /// Acquire the latest presentable frame for a slot. The returned view borrows
  /// memory owned by the engine. The caller must call photo_slot_release exactly
  /// once with the returned release_ctx. Returns false if no frame is yet
  /// available; in that case *out is zeroed and release is not required.
  ///
  /// Thread-safety: callable from any thread. Typically called from the platform
  /// texture callback (macOS raster thread / Windows render thread).
  bool photo_slot_acquire_latest(
    ffi.Pointer<photo_engine_t> engine,
    int slot_id,
    ffi.Pointer<photo_frame_view_t> out,
  ) {
    return _photo_slot_acquire_latest(
      engine,
      slot_id,
      out,
    );
  }

  late final _photo_slot_acquire_latestPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<photo_frame_view_t>)>>('photo_slot_acquire_latest');
  late final _photo_slot_acquire_latest =
      _photo_slot_acquire_latestPtr.asFunction<
          bool Function(ffi.Pointer<photo_engine_t>, int,
              ffi.Pointer<photo_frame_view_t>)>();

  void photo_slot_release(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Void> release_ctx,
  ) {
    return _photo_slot_release(
      engine,
      release_ctx,
    );
  }

  late final _photo_slot_releasePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Void>)>>('photo_slot_release');
  late final _photo_slot_release = _photo_slot_releasePtr.asFunction<
      void Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Void>)>();

  /// Drain up to `cap` events into `out`. Returns the number written. Drains in
  /// FIFO order. Safe to call from one thread only (designed as SPSC: Dart pump
  /// is the single consumer).
  int photo_poll_events(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_event_t> out,
    int cap,
  ) {
    return _photo_poll_events(
      engine,
      out,
      cap,
    );
  }

  late final _photo_poll_eventsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_event_t>, ffi.Size)>>('photo_poll_events');
  late final _photo_poll_events = _photo_poll_eventsPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_event_t>, int)>();

  /// Begin importing photos from a path. If the path is a file, imports that
  /// one asset; if a directory, recurses. Returns a non-zero job ID; progress
  /// is reported via PHOTO_EVT_IMPORT_PROGRESS and PHOTO_EVT_IMPORT_COMPLETE
  /// events whose request_id matches the returned job ID.
  ///
  /// flags: reserved; pass 0.
  int photo_import_path(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> path_utf8,
    int flags,
  ) {
    return _photo_import_path(
      engine,
      path_utf8,
      flags,
    );
  }

  late final _photo_import_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>, ffi.Uint32)>>('photo_import_path');
  late final _photo_import_path = _photo_import_pathPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>, int)>();

  /// Re-scan all previously imported locations for changes (added/removed/modified
  /// files). Returns a job ID. Progress events as above.
  int photo_rescan(
    ffi.Pointer<photo_engine_t> engine,
    int flags,
  ) {
    return _photo_rescan(
      engine,
      flags,
    );
  }

  late final _photo_rescanPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>, ffi.Uint32)>>('photo_rescan');
  late final _photo_rescan = _photo_rescanPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  /// List catalog assets (hidden excluded), ordered by path. Fills up to `cap`
  /// rows into `out` and returns the TOTAL count available — grow and re-call if
  /// it exceeds `cap`, mirroring the photo_face_list_* calls. Synchronous.
  int photo_list_assets(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_asset_t> out,
    int cap,
  ) {
    return _photo_list_assets(
      engine,
      out,
      cap,
    );
  }

  late final _photo_list_assetsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_asset_t>, ffi.Size)>>('photo_list_assets');
  late final _photo_list_assets = _photo_list_assetsPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_asset_t>, int)>();

  /// Read stored EXIF metadata for an asset into *out. Returns PHOTO_STATUS_OK,
  /// PHOTO_STATUS_NOT_FOUND if the asset has no metadata row, or an error code.
  /// Synchronous.
  int photo_asset_metadata(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<photo_metadata_t> out,
  ) {
    return _photo_asset_metadata(
      engine,
      asset_id,
      out,
    );
  }

  late final _photo_asset_metadataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<photo_metadata_t>)>>('photo_asset_metadata');
  late final _photo_asset_metadata = _photo_asset_metadataPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, ffi.Pointer<photo_metadata_t>)>();

  /// List every geotagged asset (those with GPS EXIF). Fills up to `cap` rows and
  /// returns the TOTAL count available — grow and re-call if it exceeds `cap`.
  /// Synchronous. Drives the map.
  int photo_list_geotagged(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_geopoint_t> out,
    int cap,
  ) {
    return _photo_list_geotagged(
      engine,
      out,
      cap,
    );
  }

  late final _photo_list_geotaggedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_geopoint_t>,
              ffi.Size)>>('photo_list_geotagged');
  late final _photo_list_geotagged = _photo_list_geotaggedPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_geopoint_t>, int)>();

  /// Create an album; returns its id (0 on failure / no catalog).
  int photo_album_create(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> name_utf8,
  ) {
    return _photo_album_create(
      engine,
      name_utf8,
    );
  }

  late final _photo_album_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>)>>('photo_album_create');
  late final _photo_album_create = _photo_album_createPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>)>();

  /// The mutators return photo_status_t (0 == OK).
  int photo_album_rename(
    ffi.Pointer<photo_engine_t> engine,
    int album_id,
    ffi.Pointer<ffi.Char> name_utf8,
  ) {
    return _photo_album_rename(
      engine,
      album_id,
      name_utf8,
    );
  }

  late final _photo_album_renamePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>)>>('photo_album_rename');
  late final _photo_album_rename = _photo_album_renamePtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  int photo_album_delete(
    ffi.Pointer<photo_engine_t> engine,
    int album_id,
  ) {
    return _photo_album_delete(
      engine,
      album_id,
    );
  }

  late final _photo_album_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<photo_engine_t>, ffi.Uint64)>>('photo_album_delete');
  late final _photo_album_delete = _photo_album_deletePtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  int photo_album_set_cover(
    ffi.Pointer<photo_engine_t> engine,
    int album_id,
    int cover_asset_id,
  ) {
    return _photo_album_set_cover(
      engine,
      album_id,
      cover_asset_id,
    );
  }

  late final _photo_album_set_coverPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Uint64)>>('photo_album_set_cover');
  late final _photo_album_set_cover = _photo_album_set_coverPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  int photo_album_add(
    ffi.Pointer<photo_engine_t> engine,
    int album_id,
    int asset_id,
  ) {
    return _photo_album_add(
      engine,
      album_id,
      asset_id,
    );
  }

  late final _photo_album_addPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Uint64)>>('photo_album_add');
  late final _photo_album_add = _photo_album_addPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  int photo_album_remove(
    ffi.Pointer<photo_engine_t> engine,
    int album_id,
    int asset_id,
  ) {
    return _photo_album_remove(
      engine,
      album_id,
      asset_id,
    );
  }

  late final _photo_album_removePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Uint64)>>('photo_album_remove');
  late final _photo_album_remove = _photo_album_removePtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  /// List all albums (ordered by creation). Fills up to `cap`, returns total.
  int photo_album_list(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_album_t> out,
    int cap,
  ) {
    return _photo_album_list(
      engine,
      out,
      cap,
    );
  }

  late final _photo_album_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_album_t>, ffi.Size)>>('photo_album_list');
  late final _photo_album_list = _photo_album_listPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_album_t>, int)>();

  /// Member asset ids of one album, in order. Fills up to `cap`, returns total.
  int photo_album_members(
    ffi.Pointer<photo_engine_t> engine,
    int album_id,
    ffi.Pointer<ffi.Uint64> out,
    int cap,
  ) {
    return _photo_album_members(
      engine,
      album_id,
      out,
      cap,
    );
  }

  late final _photo_album_membersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Uint64>, ffi.Size)>>('photo_album_members');
  late final _photo_album_members = _photo_album_membersPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Uint64>, int)>();

  /// The `limit` most-recently-imported asset ids, newest first.
  int photo_smart_recent(
    ffi.Pointer<photo_engine_t> engine,
    int limit,
    ffi.Pointer<ffi.Uint64> out,
    int cap,
  ) {
    return _photo_smart_recent(
      engine,
      limit,
      out,
      cap,
    );
  }

  late final _photo_smart_recentPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Int32,
              ffi.Pointer<ffi.Uint64>, ffi.Size)>>('photo_smart_recent');
  late final _photo_smart_recent = _photo_smart_recentPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Uint64>, int)>();

  /// Every starred asset id.
  int photo_smart_starred(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Uint64> out,
    int cap,
  ) {
    return _photo_smart_starred(
      engine,
      out,
      cap,
    );
  }

  late final _photo_smart_starredPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Uint64>, ffi.Size)>>('photo_smart_starred');
  late final _photo_smart_starred = _photo_smart_starredPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Uint64>, int)>();

  /// ------------------------------------------------------------------------- */
  /// /* Organize state — star / rating / caption / tags.                          */
  /// /*                                                                           */
  /// /* All catalog-only: per DECISIONS D1, user-authored metadata is NOT written  */
  /// /* back to the original files in v1. The mutators return photo_status_t.      */
  /// /* -------------------------------------------------------------------------
  int photo_asset_set_starred(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    int starred,
  ) {
    return _photo_asset_set_starred(
      engine,
      asset_id,
      starred,
    );
  }

  late final _photo_asset_set_starredPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Int32)>>('photo_asset_set_starred');
  late final _photo_asset_set_starred = _photo_asset_set_starredPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  int photo_asset_set_rating(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    int rating,
  ) {
    return _photo_asset_set_rating(
      engine,
      asset_id,
      rating,
    );
  }

  late final _photo_asset_set_ratingPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Int32)>>('photo_asset_set_rating');
  late final _photo_asset_set_rating = _photo_asset_set_ratingPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  int photo_asset_set_caption(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> caption_utf8,
  ) {
    return _photo_asset_set_caption(
      engine,
      asset_id,
      caption_utf8,
    );
  }

  late final _photo_asset_set_captionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>)>>('photo_asset_set_caption');
  late final _photo_asset_set_caption = _photo_asset_set_captionPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  /// Hide/unhide a single asset (excludes it from photo_list_assets).
  int photo_asset_set_hidden(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    int hidden,
  ) {
    return _photo_asset_set_hidden(
      engine,
      asset_id,
      hidden,
    );
  }

  late final _photo_asset_set_hiddenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Int32)>>('photo_asset_set_hidden');
  late final _photo_asset_set_hidden = _photo_asset_set_hiddenPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  /// ------------------------------------------------------------------------- */
  /// /* Folder-level hide.                                                         */
  /// /*                                                                           */
  /// /* Hiding a folder records a persistent rule (assets re-imported beneath it   */
  /// /* stay hidden) AND sweeps existing assets at/under it hidden; un-hiding      */
  /// /* sweeps them visible. Matched on a separator boundary so /a/photos never    */
  /// /* matches /a/photoshop.                                                      */
  /// /* -------------------------------------------------------------------------
  int photo_folder_set_hidden(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> path_utf8,
    int hidden,
  ) {
    return _photo_folder_set_hidden(
      engine,
      path_utf8,
      hidden,
    );
  }

  late final _photo_folder_set_hiddenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Int32)>>('photo_folder_set_hidden');
  late final _photo_folder_set_hidden = _photo_folder_set_hiddenPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>, int)>();

  /// Hidden folder paths as NUL-separated UTF-8 ("/a\0/b\0…"). Fills up to `cap`
  /// bytes into `out` and returns the TOTAL bytes needed — grow and re-call.
  int photo_hidden_folders(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> out,
    int cap,
  ) {
    return _photo_hidden_folders(
      engine,
      out,
      cap,
    );
  }

  late final _photo_hidden_foldersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Size)>>('photo_hidden_folders');
  late final _photo_hidden_folders = _photo_hidden_foldersPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>, int)>();

  /// Paths of individually-hidden assets as NUL-separated UTF-8. Same buffer
  /// protocol. photo_list_assets excludes hidden assets, so this is how the UI
  /// hydrates its hide filter on startup.
  int photo_hidden_assets(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> out,
    int cap,
  ) {
    return _photo_hidden_assets(
      engine,
      out,
      cap,
    );
  }

  late final _photo_hidden_assetsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Size)>>('photo_hidden_assets');
  late final _photo_hidden_assets = _photo_hidden_assetsPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>, int)>();

  /// Read catalog size stats into *out. Returns photo_status_t. Synchronous.
  int photo_catalog_stats(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_catalog_stats_t> out,
  ) {
    return _photo_catalog_stats(
      engine,
      out,
    );
  }

  late final _photo_catalog_statsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_catalog_stats_t>)>>('photo_catalog_stats');
  late final _photo_catalog_stats = _photo_catalog_statsPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_catalog_stats_t>)>();

  /// Checkpoint the WAL then VACUUM, on the idle lane (VACUUM can be slow).
  /// Returns a request id; emits PHOTO_EVT_MAINTENANCE_COMPLETE on completion.
  int photo_catalog_compact(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_catalog_compact(
      engine,
    );
  }

  late final _photo_catalog_compactPtr = _lookup<
          ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_catalog_compact');
  late final _photo_catalog_compact = _photo_catalog_compactPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>)>();

  /// Synchronous checkpoint + VACUUM (blocks until done). For on-exit cleanup,
  /// where the async lane wouldn't finish before the process tears down.
  int photo_catalog_compact_sync(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_catalog_compact_sync(
      engine,
    );
  }

  late final _photo_catalog_compact_syncPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_catalog_compact_sync');
  late final _photo_catalog_compact_sync = _photo_catalog_compact_syncPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>)>();

  /// Flush the WAL into the main DB and truncate it (cheap; pre-copy helper).
  int photo_catalog_checkpoint(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_catalog_checkpoint(
      engine,
    );
  }

  late final _photo_catalog_checkpointPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_catalog_checkpoint');
  late final _photo_catalog_checkpoint = _photo_catalog_checkpointPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>)>();

  /// ------------------------------------------------------------------------- */
  /// /* Relocate — rebase asset paths after the photo library moved on disk.       */
  /// /* ------------------------------------------------------------------------- */
  /// /*
  /// Rewrite every stored path at/under old_prefix to sit under new_prefix
  /// instead, preserving asset ids so faces/albums/tags survive the move.
  /// new_prefix must exist on disk. Returns photo_status_t (NOT_FOUND when the new
  /// root is missing). Synchronous + transactional.
  int photo_library_rebase(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> old_prefix_utf8,
    ffi.Pointer<ffi.Char> new_prefix_utf8,
  ) {
    return _photo_library_rebase(
      engine,
      old_prefix_utf8,
      new_prefix_utf8,
    );
  }

  late final _photo_library_rebasePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('photo_library_rebase');
  late final _photo_library_rebase = _photo_library_rebasePtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// Relocate individual assets after their files moved on disk, preserving
  /// asset ids (faces/albums/tags/edits/embeddings stay attached). `asset_ids`
  /// is `count` ids; `new_paths_utf8` is `count` NUL-terminated absolute paths
  /// back-to-back ("a\0b\0…"). A row is skipped (not fatal) when its id is
  /// unknown, its path is unchanged, or the destination collides with a
  /// different existing asset. `out_ok` (optional, `count` bytes) receives 1/0
  /// per row; `out_applied` (optional) the number updated. Synchronous +
  /// transactional. Returns photo_status_t.
  int photo_assets_relocate(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Uint64> asset_ids,
    ffi.Pointer<ffi.Char> new_paths_utf8,
    int count,
    ffi.Pointer<ffi.Uint8> out_ok,
    ffi.Pointer<ffi.Uint64> out_applied,
  ) {
    return _photo_assets_relocate(
      engine,
      asset_ids,
      new_paths_utf8,
      count,
      out_ok,
      out_applied,
    );
  }

  late final _photo_assets_relocatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Uint64>,
              ffi.Pointer<ffi.Char>,
              ffi.Size,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint64>)>>('photo_assets_relocate');
  late final _photo_assets_relocate = _photo_assets_relocatePtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>,
          ffi.Pointer<ffi.Uint64>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint64>)>();

  int photo_asset_organize(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<photo_organize_t> out,
  ) {
    return _photo_asset_organize(
      engine,
      asset_id,
      out,
    );
  }

  late final _photo_asset_organizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<photo_organize_t>)>>('photo_asset_organize');
  late final _photo_asset_organize = _photo_asset_organizePtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, ffi.Pointer<photo_organize_t>)>();

  int photo_asset_add_tag(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> tag_utf8,
  ) {
    return _photo_asset_add_tag(
      engine,
      asset_id,
      tag_utf8,
    );
  }

  late final _photo_asset_add_tagPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>)>>('photo_asset_add_tag');
  late final _photo_asset_add_tag = _photo_asset_add_tagPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  int photo_asset_remove_tag(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> tag_utf8,
  ) {
    return _photo_asset_remove_tag(
      engine,
      asset_id,
      tag_utf8,
    );
  }

  late final _photo_asset_remove_tagPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>)>>('photo_asset_remove_tag');
  late final _photo_asset_remove_tag = _photo_asset_remove_tagPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  /// Tags of an asset as NUL-separated UTF-8 ("tag1\0tag2\0…"). Fills up to `cap`
  /// bytes into `out` and returns the TOTAL bytes needed — grow and re-call if it
  /// exceeds `cap`.
  int photo_asset_tags(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> out,
    int cap,
  ) {
    return _photo_asset_tags(
      engine,
      asset_id,
      out,
      cap,
    );
  }

  late final _photo_asset_tagsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>, ffi.Size)>>('photo_asset_tags');
  late final _photo_asset_tags = _photo_asset_tagsPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>, int)>();

  /// Serialized edit spec for an asset into a caller buffer (NUL-terminated UTF-8).
  /// Returns the total bytes needed INCLUDING the NUL — grow and re-call if it
  /// exceeds `cap` (mirrors photo_asset_tags). Empty (returns 1, a lone NUL) when
  /// the asset is unedited.
  int photo_asset_get_edits(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> out,
    int cap,
  ) {
    return _photo_asset_get_edits(
      engine,
      asset_id,
      out,
      cap,
    );
  }

  late final _photo_asset_get_editsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>, ffi.Size)>>('photo_asset_get_edits');
  late final _photo_asset_get_edits = _photo_asset_get_editsPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>, int)>();

  /// Persist the edit spec and bump content_rev. Returns the NEW content_rev, or 0
  /// if the spec is identity (the edit is cleared) or on failure / no catalog.
  ///
  /// NB the engine has no asset->slot index by design, so it cannot self-invalidate
  /// a visible tile. The caller MUST rebind the affected slot's generation and
  /// re-request off the returned content_rev so the gallery / lightbox repaint —
  /// a same-asset save does not otherwise bump the slot generation, and an
  /// in-flight original-keyed request could publish the pre-edit frame after this
  /// returns.
  int photo_asset_set_edits(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> spec_utf8,
  ) {
    return _photo_asset_set_edits(
      engine,
      asset_id,
      spec_utf8,
    );
  }

  late final _photo_asset_set_editsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>)>>('photo_asset_set_edits');
  late final _photo_asset_set_edits = _photo_asset_set_editsPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  /// Clear the saved edit (revert to original). Returns photo_status_t.
  int photo_asset_revert(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
  ) {
    return _photo_asset_revert(
      engine,
      asset_id,
    );
  }

  late final _photo_asset_revertPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<photo_engine_t>, ffi.Uint64)>>('photo_asset_revert');
  late final _photo_asset_revert = _photo_asset_revertPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  /// Current content_rev for an asset (0 = unedited / no saved edit).
  int photo_asset_content_rev(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
  ) {
    return _photo_asset_content_rev(
      engine,
      asset_id,
    );
  }

  late final _photo_asset_content_revPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>,
              ffi.Uint64)>>('photo_asset_content_rev');
  late final _photo_asset_content_rev = _photo_asset_content_revPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  /// Render `spec` over a FULL-RESOLUTION decode of `src_path` and write a flattened
  /// copy to `dst_path` (format chosen by extension: .jpg/.jpeg honour `quality`
  /// 1..100; .png/.tif also supported). This is "Save as Copy" — the original is
  /// untouched. Async on the idle lane: returns a non-zero request id and emits
  /// PHOTO_EVT_EXPORT_COMPLETE with the same id (status = result). Returns 0 on
  /// immediate rejection. PHOTO_STATUS_UNSUPPORTED-equivalent (0) without libvips.
  int photo_asset_export(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> src_path_utf8,
    ffi.Pointer<ffi.Char> dst_path_utf8,
    ffi.Pointer<ffi.Char> spec_utf8,
    int quality,
  ) {
    return _photo_asset_export(
      engine,
      src_path_utf8,
      dst_path_utf8,
      spec_utf8,
      quality,
    );
  }

  late final _photo_asset_exportPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32)>>('photo_asset_export');
  late final _photo_asset_export = _photo_asset_exportPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  /// photo_asset_export with output options. `opts` may be NULL (exact legacy
  /// photo_asset_export behaviour at quality 92). Same async request-id +
  /// PHOTO_EVT_EXPORT_COMPLETE contract; 0 without libvips.
  int photo_asset_export2(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> src_path_utf8,
    ffi.Pointer<ffi.Char> dst_path_utf8,
    ffi.Pointer<ffi.Char> spec_utf8,
    ffi.Pointer<photo_export_options_t> opts,
  ) {
    return _photo_asset_export2(
      engine,
      src_path_utf8,
      dst_path_utf8,
      spec_utf8,
      opts,
    );
  }

  late final _photo_asset_export2Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<photo_export_options_t>)>>('photo_asset_export2');
  late final _photo_asset_export2 = _photo_asset_export2Ptr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<photo_export_options_t>)>();

  /// Composite `cells` onto a `canvas_w × canvas_h` canvas filled with `bg_rgb`
  /// (0xRRGGBB) and write a JPEG to `dst_path` (jpg `quality`). Each source is
  /// rendered full-res and cover-fit into its cell. Async on the idle lane: returns
  /// a request id + emits PHOTO_EVT_EXPORT_COMPLETE. 0 on rejection / no libvips.
  int photo_create_collage(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_collage_cell_t> cells,
    int count,
    ffi.Pointer<ffi.Char> dst_path_utf8,
    int canvas_w,
    int canvas_h,
    int bg_rgb,
    int quality,
  ) {
    return _photo_create_collage(
      engine,
      cells,
      count,
      dst_path_utf8,
      canvas_w,
      canvas_h,
      bg_rgb,
      quality,
    );
  }

  late final _photo_create_collagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_collage_cell_t>,
              ffi.Size,
              ffi.Pointer<ffi.Char>,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Int32)>>('photo_create_collage');
  late final _photo_create_collage = _photo_create_collagePtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>,
          ffi.Pointer<photo_collage_cell_t>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
          int)>();

  /// §11 video trim (non-destructive, catalog-only). set(0,0) clears. get fills
  /// *start_ms / *end_ms (end 0 = to the end; both 0 = no trim); returns
  /// photo_status_t. export_trimmed stream-copies [start,end) of `src` to `dst`
  /// (no re-encode) on the idle lane, sharing the export event stream.
  int photo_video_set_trim(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    int start_ms,
    int end_ms,
  ) {
    return _photo_video_set_trim(
      engine,
      asset_id,
      start_ms,
      end_ms,
    );
  }

  late final _photo_video_set_trimPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64, ffi.Int64,
              ffi.Int64)>>('photo_video_set_trim');
  late final _photo_video_set_trim = _photo_video_set_trimPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int, int)>();

  int photo_video_get_trim(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Int64> start_ms,
    ffi.Pointer<ffi.Int64> end_ms,
  ) {
    return _photo_video_get_trim(
      engine,
      asset_id,
      start_ms,
      end_ms,
    );
  }

  late final _photo_video_get_trimPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Uint64,
              ffi.Pointer<ffi.Int64>,
              ffi.Pointer<ffi.Int64>)>>('photo_video_get_trim');
  late final _photo_video_get_trim = _photo_video_get_trimPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Int64>,
          ffi.Pointer<ffi.Int64>)>();

  int photo_video_export_trimmed(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> src_path_utf8,
    ffi.Pointer<ffi.Char> dst_path_utf8,
    int start_ms,
    int end_ms,
  ) {
    return _photo_video_export_trimmed(
      engine,
      src_path_utf8,
      dst_path_utf8,
      start_ms,
      end_ms,
    );
  }

  late final _photo_video_export_trimmedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int64,
              ffi.Int64)>>('photo_video_export_trimmed');
  late final _photo_video_export_trimmed =
      _photo_video_export_trimmedPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, int, int)>();

  /// Save mode `layeredTiff`: write a self-contained multi-page TIFF to `dst_path`
  /// — page 0 = the edited render, page 1 = the UNTOUCHED original, with the
  /// parametric spec embedded as XMP. Reversible from the file itself (drop the
  /// layer → re-derive from page 1). Async; same request-id + PHOTO_EVT_EXPORT_-
  /// COMPLETE contract as photo_asset_export.
  int photo_asset_save_layered(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> src_path_utf8,
    ffi.Pointer<ffi.Char> dst_path_utf8,
    ffi.Pointer<ffi.Char> spec_utf8,
  ) {
    return _photo_asset_save_layered(
      engine,
      src_path_utf8,
      dst_path_utf8,
      spec_utf8,
    );
  }

  late final _photo_asset_save_layeredPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('photo_asset_save_layered');
  late final _photo_asset_save_layered =
      _photo_asset_save_layeredPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Asset ids that currently have a saved (non-identity) edit, for the gallery's
  /// "edited" badge. Fills up to `cap` ids and returns the TOTAL available — grow
  /// and re-call if it exceeds `cap` (mirrors photo_album_members).
  int photo_list_edited_assets(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Uint64> out,
    int cap,
  ) {
    return _photo_list_edited_assets(
      engine,
      out,
      cap,
    );
  }

  late final _photo_list_edited_assetsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Uint64>, ffi.Size)>>('photo_list_edited_assets');
  late final _photo_list_edited_assets =
      _photo_list_edited_assetsPtr.asFunction<
          int Function(
              ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Uint64>, int)>();

  /// Render a TRANSIENT spec to a slot for live preview: no cache write, no catalog
  /// write. The result is published as a PHOTO_STAGE_FULL frame and announced via
  /// PHOTO_EVT_STAGE_READY with request_id 0 and the echoed `generation` (dropped
  /// on a generation mismatch, so rapid asset-switching in the editor is safe).
  /// Returns photo_status_t (PHOTO_STATUS_UNSUPPORTED when built without libvips).
  int photo_asset_preview_edits(
    ffi.Pointer<photo_engine_t> engine,
    int slot_id,
    int generation,
    ffi.Pointer<ffi.Char> path_utf8,
    int target_w,
    int target_h,
    ffi.Pointer<ffi.Char> spec_utf8,
  ) {
    return _photo_asset_preview_edits(
      engine,
      slot_id,
      generation,
      path_utf8,
      target_w,
      target_h,
      spec_utf8,
    );
  }

  late final _photo_asset_preview_editsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Pointer<ffi.Char>,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Pointer<ffi.Char>)>>('photo_asset_preview_edits');
  late final _photo_asset_preview_edits =
      _photo_asset_preview_editsPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, int, int,
              ffi.Pointer<ffi.Char>, int, int, ffi.Pointer<ffi.Char>)>();

  /// Red-eye AUTO-DETECT: decode `path`, look up the asset's stored eye landmarks
  /// (from the face scan), and fill `out` with a red-eye brush region for every eye
  /// that actually contains a red pupil (non-red eyes are skipped). The caller adds
  /// these to the edit spec's `redeye=` list — same non-destructive path as manual
  /// dabs. `spec_utf8` is the caller's CURRENT working edit spec (may be NULL/"");
  /// when it carries geometry (crop/rotate/flip/straighten) the regions are mapped
  /// into that post-geometry space, and eyes cropped out of frame are dropped.
  /// Fills up to `cap` and returns the TOTAL found — grow and re-call if it
  /// exceeds `cap` (mirrors photo_list_edited_assets). Returns 0 without the face
  /// models (Linux/Windows plugins) or when no eye is red; caller falls back to the
  /// manual brush. Synchronous (does a full-res decode) — call off the UI thread.
  int photo_asset_detect_redeye(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> path_utf8,
    ffi.Pointer<ffi.Char> spec_utf8,
    ffi.Pointer<photo_region_t> out,
    int cap,
  ) {
    return _photo_asset_detect_redeye(
      engine,
      asset_id,
      path_utf8,
      spec_utf8,
      out,
      cap,
    );
  }

  late final _photo_asset_detect_redeyePtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Uint64,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<photo_region_t>,
              ffi.Size)>>('photo_asset_detect_redeye');
  late final _photo_asset_detect_redeye =
      _photo_asset_detect_redeyePtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<photo_region_t>, int)>();

  /// Whether this build can auto-detect red-eye at all (face models compiled in).
  /// Compile-time capability, not per-asset: 0 on the Linux/Windows plugins, 1 on
  /// macOS/standalone. Lets the UI say "not available on this platform" instead of
  /// a misleading "no red-eye detected".
  int photo_redeye_auto_supported() {
    return _photo_redeye_auto_supported();
  }

  late final _photo_redeye_auto_supportedPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
          'photo_redeye_auto_supported');
  late final _photo_redeye_auto_supported =
      _photo_redeye_auto_supportedPtr.asFunction<int Function()>();

  /// Schedule a face scan for an asset. Detection -> alignment -> embedding,
  /// with results stored in the catalog. Emits PHOTO_EVT_SCAN_PROGRESS while
  /// running. Returns a job ID.
  int photo_face_scan(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    int flags,
  ) {
    return _photo_face_scan(
      engine,
      asset_id,
      flags,
    );
  }

  late final _photo_face_scanPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Uint32)>>('photo_face_scan');
  late final _photo_face_scan = _photo_face_scanPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  /// ------------------------------------------------------------------------- */
  /// /* Clustering (added in M7)                                                  */
  /// /* -------------------------------------------------------------------------
  int photo_face_approve(
    ffi.Pointer<photo_engine_t> engine,
    int cluster_id,
    int embedding_id,
  ) {
    return _photo_face_approve(
      engine,
      cluster_id,
      embedding_id,
    );
  }

  late final _photo_face_approvePtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Uint64)>>('photo_face_approve');
  late final _photo_face_approve = _photo_face_approvePtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  int photo_face_reject(
    ffi.Pointer<photo_engine_t> engine,
    int cluster_id,
    int embedding_id,
  ) {
    return _photo_face_reject(
      engine,
      cluster_id,
      embedding_id,
    );
  }

  late final _photo_face_rejectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Uint64)>>('photo_face_reject');
  late final _photo_face_reject = _photo_face_rejectPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  /// Trigger a full HDBSCAN rebuild. Expensive (minutes on a large library).
  /// Runs in the idle lane. Emits PHOTO_EVT_CLUSTER_UPDATED on completion.
  int photo_cluster_rebuild(
    ffi.Pointer<photo_engine_t> engine,
    int flags,
  ) {
    return _photo_cluster_rebuild(
      engine,
      flags,
    );
  }

  late final _photo_cluster_rebuildPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>,
              ffi.Uint32)>>('photo_cluster_rebuild');
  late final _photo_cluster_rebuild = _photo_cluster_rebuildPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  /// Promote an unconfirmed cluster into a named person: confirms every face in
  /// `cluster_id` into a person named `name_utf8`, merging into an existing person
  /// of the same name or creating a new one. Runs in the idle lane; emits
  /// PHOTO_EVT_CLUSTER_UPDATED on completion. Returns a request id.
  int photo_face_name_cluster(
    ffi.Pointer<photo_engine_t> engine,
    int cluster_id,
    ffi.Pointer<ffi.Char> name_utf8,
  ) {
    return _photo_face_name_cluster(
      engine,
      cluster_id,
      name_utf8,
    );
  }

  late final _photo_face_name_clusterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>, ffi.Int64,
              ffi.Pointer<ffi.Char>)>>('photo_face_name_cluster');
  late final _photo_face_name_cluster = _photo_face_name_clusterPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  /// Confirmed/named people.
  int photo_face_list_people(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_person_t> out,
    int cap,
  ) {
    return _photo_face_list_people(
      engine,
      out,
      cap,
    );
  }

  late final _photo_face_list_peoplePtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_person_t>,
              ffi.Size)>>('photo_face_list_people');
  late final _photo_face_list_people = _photo_face_list_peoplePtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_person_t>, int)>();

  /// Unconfirmed cluster buckets (the "unnamed faces" groups), as person rows
  /// (person_id == 0, cluster_id set, name empty).
  int photo_face_list_clusters(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_person_t> out,
    int cap,
  ) {
    return _photo_face_list_clusters(
      engine,
      out,
      cap,
    );
  }

  late final _photo_face_list_clustersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_person_t>,
              ffi.Size)>>('photo_face_list_clusters');
  late final _photo_face_list_clusters =
      _photo_face_list_clustersPtr.asFunction<
          int Function(
              ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_person_t>, int)>();

  /// Members of one cluster (confirmed + suggested), highest quality first.
  int photo_face_list_cluster_faces(
    ffi.Pointer<photo_engine_t> engine,
    int cluster_id,
    ffi.Pointer<photo_face_t> out,
    int cap,
  ) {
    return _photo_face_list_cluster_faces(
      engine,
      cluster_id,
      out,
      cap,
    );
  }

  late final _photo_face_list_cluster_facesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Int64,
              ffi.Pointer<photo_face_t>,
              ffi.Size)>>('photo_face_list_cluster_faces');
  late final _photo_face_list_cluster_faces =
      _photo_face_list_cluster_facesPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, int,
              ffi.Pointer<photo_face_t>, int)>();

  /// Unconfirmed (suggested) faces for a person — the suggest-and-confirm queue.
  int photo_face_list_suggestions(
    ffi.Pointer<photo_engine_t> engine,
    int person_id,
    ffi.Pointer<photo_face_t> out,
    int cap,
  ) {
    return _photo_face_list_suggestions(
      engine,
      person_id,
      out,
      cap,
    );
  }

  late final _photo_face_list_suggestionsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Uint64,
              ffi.Pointer<photo_face_t>,
              ffi.Size)>>('photo_face_list_suggestions');
  late final _photo_face_list_suggestions =
      _photo_face_list_suggestionsPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, int,
              ffi.Pointer<photo_face_t>, int)>();

  /// Faces detected in one asset (drives the info-panel People tab).
  int photo_face_list_for_asset(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<photo_face_t> out,
    int cap,
  ) {
    return _photo_face_list_for_asset(
      engine,
      asset_id,
      out,
      cap,
    );
  }

  late final _photo_face_list_for_assetPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Uint64,
              ffi.Pointer<photo_face_t>,
              ffi.Size)>>('photo_face_list_for_asset');
  late final _photo_face_list_for_asset =
      _photo_face_list_for_assetPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, int,
              ffi.Pointer<photo_face_t>, int)>();

  /// Name (or rename) a person. Returns photo_status_t.
  int photo_face_name_person(
    ffi.Pointer<photo_engine_t> engine,
    int person_id,
    ffi.Pointer<ffi.Char> name_utf8,
  ) {
    return _photo_face_name_person(
      engine,
      person_id,
      name_utf8,
    );
  }

  late final _photo_face_name_personPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>)>>('photo_face_name_person');
  late final _photo_face_name_person = _photo_face_name_personPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  /// Schedule embedding for one asset on the idle lane. Emits PHOTO_EVT_EMBED_PROGRESS
  /// on completion. Returns a request id (0 if no catalog / no embedder). Idempotent
  /// at the pipeline level: callers build the work list from photo_embedding_pending.
  int photo_embedding_scan(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
  ) {
    return _photo_embedding_scan(
      engine,
      asset_id,
    );
  }

  late final _photo_embedding_scanPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>,
              ffi.Uint64)>>('photo_embedding_scan');
  late final _photo_embedding_scan = _photo_embedding_scanPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  int photo_embedding_counts(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_embed_counts_t> out,
  ) {
    return _photo_embedding_counts(
      engine,
      out,
    );
  }

  late final _photo_embedding_countsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_embed_counts_t>)>>('photo_embedding_counts');
  late final _photo_embedding_counts = _photo_embedding_countsPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, ffi.Pointer<photo_embed_counts_t>)>();

  /// Asset ids that still need embedding for the ACTIVE model — the resume queue.
  /// Fills up to `cap` and returns the TOTAL available (grow + re-call). limit<0
  /// means no server-side cap.
  int photo_embedding_pending(
    ffi.Pointer<photo_engine_t> engine,
    int limit,
    ffi.Pointer<ffi.Uint64> out,
    int cap,
  ) {
    return _photo_embedding_pending(
      engine,
      limit,
      out,
      cap,
    );
  }

  late final _photo_embedding_pendingPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Int32,
              ffi.Pointer<ffi.Uint64>, ffi.Size)>>('photo_embedding_pending');
  late final _photo_embedding_pending = _photo_embedding_pendingPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Uint64>, int)>();

  /// Flip every failed embedding back to pending (an explicit "retry failed").
  int photo_embedding_retry_failed(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_embedding_retry_failed(
      engine,
    );
  }

  late final _photo_embedding_retry_failedPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_embedding_retry_failed');
  late final _photo_embedding_retry_failed = _photo_embedding_retry_failedPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>)>();

  int photo_embedding_colors(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_asset_color_t> out,
    int cap,
  ) {
    return _photo_embedding_colors(
      engine,
      out,
      cap,
    );
  }

  late final _photo_embedding_colorsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_asset_color_t>,
              ffi.Size)>>('photo_embedding_colors');
  late final _photo_embedding_colors = _photo_embedding_colorsPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>,
          ffi.Pointer<photo_asset_color_t>, int)>();

  /// Embed a text query into the active model's vector space. Writes up to `cap`
  /// floats into `out_vec` and returns the model dimensionality (which may exceed
  /// `cap` — grow + re-call). Returns 0 if there is no embedder.
  int photo_embed_text(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> query_utf8,
    ffi.Pointer<ffi.Float> out_vec,
    int cap,
  ) {
    return _photo_embed_text(
      engine,
      query_utf8,
      out_vec,
      cap,
    );
  }

  late final _photo_embed_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Float>,
              ffi.Uint32)>>('photo_embed_text');
  late final _photo_embed_text = _photo_embed_textPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Float>, int)>();

  /// Cosine-rank `query_vec` (dim floats) over the done embeddings, optionally
  /// restricted to `candidates` (n_candidates asset ids; NULL/0 = all). Fills up
  /// to `cap` hits (score-descending) into `out` and returns the number written.
  int photo_semantic_search(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Float> query_vec,
    int dim,
    ffi.Pointer<ffi.Uint64> candidates,
    int n_candidates,
    ffi.Pointer<photo_search_hit_t> out,
    int cap,
  ) {
    return _photo_semantic_search(
      engine,
      query_vec,
      dim,
      candidates,
      n_candidates,
      out,
      cap,
    );
  }

  late final _photo_semantic_searchPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Float>,
              ffi.Uint32,
              ffi.Pointer<ffi.Uint64>,
              ffi.Size,
              ffi.Pointer<photo_search_hit_t>,
              ffi.Size)>>('photo_semantic_search');
  late final _photo_semantic_search = _photo_semantic_searchPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>,
          ffi.Pointer<ffi.Float>,
          int,
          ffi.Pointer<ffi.Uint64>,
          int,
          ffi.Pointer<photo_search_hit_t>,
          int)>();

  /// Reclaim the RAM of lazily-loaded semantic inference sessions. The UI calls
  /// this with ..._IMAGE when the embedding-indexing queue drains (the image
  /// tower holds ~hundreds of MB only needed while indexing) and with ..._TEXT
  /// after a search idle timeout. Safe concurrently with in-flight embeds (they
  /// complete on their own reference); the next embed/search transparently
  /// reloads from disk (~1 s). No-op for the deterministic backend.
  void photo_semantic_release_sessions(
    ffi.Pointer<photo_engine_t> engine,
    int mask,
  ) {
    return _photo_semantic_release_sessions(
      engine,
      mask,
    );
  }

  late final _photo_semantic_release_sessionsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<photo_engine_t>,
              ffi.Uint32)>>('photo_semantic_release_sessions');
  late final _photo_semantic_release_sessions =
      _photo_semantic_release_sessionsPtr
          .asFunction<void Function(ffi.Pointer<photo_engine_t>, int)>();

  /// Re-probe the models directory and swap the semantic embedder in — call after
  /// the first-run model download lands so real text→image search activates
  /// without an app restart. In-flight embeds finish on the old service. Returns
  /// the active model's dimensionality (0 if no engine). A model change re-queues
  /// stale embedding rows via photo_embedding_pending.
  int photo_semantic_reload(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_semantic_reload(
      engine,
    );
  }

  late final _photo_semantic_reloadPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_semantic_reload');
  late final _photo_semantic_reload = _photo_semantic_reloadPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>)>();

  int photo_saved_search_create(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> name_utf8,
    ffi.Pointer<ffi.Char> query_json_utf8,
  ) {
    return _photo_saved_search_create(
      engine,
      name_utf8,
      query_json_utf8,
    );
  }

  late final _photo_saved_search_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('photo_saved_search_create');
  late final _photo_saved_search_create =
      _photo_saved_search_createPtr.asFunction<
          int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>();

  int photo_saved_search_delete(
    ffi.Pointer<photo_engine_t> engine,
    int id,
  ) {
    return _photo_saved_search_delete(
      engine,
      id,
    );
  }

  late final _photo_saved_search_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>,
              ffi.Uint64)>>('photo_saved_search_delete');
  late final _photo_saved_search_delete = _photo_saved_search_deletePtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  /// List saved searches (newest first). Fills up to `cap`, returns TOTAL.
  int photo_saved_search_list(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<photo_saved_search_t> out,
    int cap,
  ) {
    return _photo_saved_search_list(
      engine,
      out,
      cap,
    );
  }

  late final _photo_saved_search_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<photo_saved_search_t>,
              ffi.Size)>>('photo_saved_search_list');
  late final _photo_saved_search_list = _photo_saved_search_listPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>,
          ffi.Pointer<photo_saved_search_t>, int)>();

  /// The opaque query_json of one saved search into `out` (NUL-terminated UTF-8).
  /// Returns the TOTAL bytes needed (grow + re-call), mirroring photo_asset_tags.
  int photo_saved_search_query(
    ffi.Pointer<photo_engine_t> engine,
    int id,
    ffi.Pointer<ffi.Char> out,
    int cap,
  ) {
    return _photo_saved_search_query(
      engine,
      id,
      out,
      cap,
    );
  }

  late final _photo_saved_search_queryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>, ffi.Size)>>('photo_saved_search_query');
  late final _photo_saved_search_query =
      _photo_saved_search_queryPtr.asFunction<
          int Function(
              ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>, int)>();

  /// Hide (ignore=1) or restore (ignore=0) a detected face. An ignored face is
  /// detached from its person/cluster and excluded from people + re-clustering
  /// (Picasa's ]ignoreface). Returns photo_status_t.
  int photo_face_set_ignored(
    ffi.Pointer<photo_engine_t> engine,
    int face_id,
    int ignored,
  ) {
    return _photo_face_set_ignored(
      engine,
      face_id,
      ignored,
    );
  }

  late final _photo_face_set_ignoredPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Int32)>>('photo_face_set_ignored');
  late final _photo_face_set_ignored = _photo_face_set_ignoredPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int, int)>();

  /// Face model registry. The active model profile is resolved by probing the
  /// models directory (model_registry.h); faces embedded by a non-active profile
  /// are STALE — excluded from prototypes/clustering until rescanned.
  /// photo_face_model_id: NUL-terminated active profile id into out (cap incl.
  /// NUL). PHOTO_STATUS_INVALID_ARG when cap is too small.
  /// photo_face_stale_count: embedded faces from non-active profiles.
  /// photo_face_prune_stale: delete UNCONFIRMED stale rows (a fresh scan
  /// repopulates them); returns rows deleted. Confirmed rows keep their
  /// person link but sit out of prototypes until rescanned.
  int photo_face_model_id(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> out,
    int cap,
  ) {
    return _photo_face_model_id(
      engine,
      out,
      cap,
    );
  }

  late final _photo_face_model_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Size)>>('photo_face_model_id');
  late final _photo_face_model_id = _photo_face_model_idPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>, int)>();

  int photo_face_stale_count(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_face_stale_count(
      engine,
    );
  }

  late final _photo_face_stale_countPtr = _lookup<
          ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_face_stale_count');
  late final _photo_face_stale_count = _photo_face_stale_countPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>)>();

  int photo_face_prune_stale(
    ffi.Pointer<photo_engine_t> engine,
  ) {
    return _photo_face_prune_stale(
      engine,
    );
  }

  late final _photo_face_prune_stalePtr = _lookup<
          ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<photo_engine_t>)>>(
      'photo_face_prune_stale');
  late final _photo_face_prune_stale = _photo_face_prune_stalePtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>)>();

  /// Analyzers — the plugin-ready per-asset analysis seam (runtime/analyzer.h).
  /// Results persist in the catalog analysis table keyed (analyzer_id, asset_id)
  /// with a small JSON payload whose schema is each analyzer's own contract.
  /// NOT yet a stable third-party API (see docs/EXTENDING.md).
  /// photo_analyzer_list: NUL-separated "id\tversion" entries into out;
  /// returns TOTAL bytes needed (grow-and-retry, like photo_asset_tags).
  /// photo_analyzer_run: schedule on the idle lane; a pending row is written
  /// immediately, the result row (status done/failed) when finished. Poll
  /// photo_analysis_get. Returns a request id; 0 = unknown/unavailable.
  /// photo_analysis_get: *out_status = 0 pending / 1 done / 2 failed;
  /// payload copied when cap >= *out_needed. NOT_FOUND when never run.
  int photo_analyzer_list(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> out,
    int cap,
  ) {
    return _photo_analyzer_list(
      engine,
      out,
      cap,
    );
  }

  late final _photo_analyzer_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>,
              ffi.Size)>>('photo_analyzer_list');
  late final _photo_analyzer_list = _photo_analyzer_listPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>, int)>();

  int photo_analyzer_run(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> analyzer_id_utf8,
    int asset_id,
  ) {
    return _photo_analyzer_run(
      engine,
      analyzer_id_utf8,
      asset_id,
    );
  }

  late final _photo_analyzer_runPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>, ffi.Uint64)>>('photo_analyzer_run');
  late final _photo_analyzer_run = _photo_analyzer_runPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, ffi.Pointer<ffi.Char>, int)>();

  int photo_analysis_get(
    ffi.Pointer<photo_engine_t> engine,
    ffi.Pointer<ffi.Char> analyzer_id_utf8,
    int asset_id,
    ffi.Pointer<ffi.Int32> out_status,
    ffi.Pointer<ffi.Char> out_payload,
    int cap,
    ffi.Pointer<ffi.Size> out_needed,
  ) {
    return _photo_analysis_get(
      engine,
      analyzer_id_utf8,
      asset_id,
      out_status,
      out_payload,
      cap,
      out_needed,
    );
  }

  late final _photo_analysis_getPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Uint64,
              ffi.Pointer<ffi.Int32>,
              ffi.Pointer<ffi.Char>,
              ffi.Size,
              ffi.Pointer<ffi.Size>)>>('photo_analysis_get');
  late final _photo_analysis_get = _photo_analysis_getPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Size>)>();

  /// Add a user-drawn face rectangle to an asset, in source-image pixels. Stores
  /// the box as a manual face (no embedding). If the face models are loaded the
  /// region is also embedded so recognition can suggest it. Returns the new
  /// face_id, or 0 on failure.
  int photo_face_add_manual(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    double box_x,
    double box_y,
    double box_w,
    double box_h,
  ) {
    return _photo_face_add_manual(
      engine,
      asset_id,
      box_x,
      box_y,
      box_w,
      box_h,
    );
  }

  late final _photo_face_add_manualPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint64 Function(
              ffi.Pointer<photo_engine_t>,
              ffi.Uint64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float)>>('photo_face_add_manual');
  late final _photo_face_add_manual = _photo_face_add_manualPtr.asFunction<
      int Function(
          ffi.Pointer<photo_engine_t>, int, double, double, double, double)>();

  /// Assign a face to a named person (create/merge by name), confirming it. Works
  /// for detector and manual faces alike. Returns photo_status_t.
  int photo_face_assign(
    ffi.Pointer<photo_engine_t> engine,
    int face_id,
    ffi.Pointer<ffi.Char> name_utf8,
  ) {
    return _photo_face_assign(
      engine,
      face_id,
      name_utf8,
    );
  }

  late final _photo_face_assignPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>)>>('photo_face_assign');
  late final _photo_face_assign = _photo_face_assignPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>)>();

  /// Hard-delete a face row (used to undo a manual rectangle). photo_status_t.
  int photo_face_remove(
    ffi.Pointer<photo_engine_t> engine,
    int face_id,
  ) {
    return _photo_face_remove(
      engine,
      face_id,
    );
  }

  late final _photo_face_removePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<photo_engine_t>, ffi.Uint64)>>('photo_face_remove');
  late final _photo_face_remove = _photo_face_removePtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();

  /// Write the asset's named face regions to an XMP sidecar ("<path>.xmp") using
  /// the MWG Regions schema (Lightroom/digiKam-readable). OPT-IN write-back per
  /// DECISIONS D1 — only ever called on explicit user action, never automatically.
  /// If out_path/out_cap are non-NULL the written sidecar path is copied there.
  /// Returns photo_status_t (NOT_FOUND when the asset has no named faces).
  int photo_asset_write_face_xmp(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    ffi.Pointer<ffi.Char> out_path,
    int out_cap,
  ) {
    return _photo_asset_write_face_xmp(
      engine,
      asset_id,
      out_path,
      out_cap,
    );
  }

  late final _photo_asset_write_face_xmpPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Pointer<ffi.Char>, ffi.Size)>>('photo_asset_write_face_xmp');
  late final _photo_asset_write_face_xmp =
      _photo_asset_write_face_xmpPtr.asFunction<
          int Function(
              ffi.Pointer<photo_engine_t>, int, ffi.Pointer<ffi.Char>, int)>();

  /// ------------------------------------------------------------------------- */
  /// /* Manual geotag — override / clear an asset's map coordinates.               */
  /// /*                                                                           */
  /// /* Catalog-only, survives rescan, and takes precedence over EXIF GPS so a     */
  /// /* user can place a photo the camera didn't tag. Feeds photo_list_geotagged.  */
  /// /* -------------------------------------------------------------------------
  int photo_asset_set_geo(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
    double lat,
    double lon,
  ) {
    return _photo_asset_set_geo(
      engine,
      asset_id,
      lat,
      lon,
    );
  }

  late final _photo_asset_set_geoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>, ffi.Uint64,
              ffi.Double, ffi.Double)>>('photo_asset_set_geo');
  late final _photo_asset_set_geo = _photo_asset_set_geoPtr.asFunction<
      int Function(ffi.Pointer<photo_engine_t>, int, double, double)>();

  int photo_asset_clear_geo(
    ffi.Pointer<photo_engine_t> engine,
    int asset_id,
  ) {
    return _photo_asset_clear_geo(
      engine,
      asset_id,
    );
  }

  late final _photo_asset_clear_geoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<photo_engine_t>,
              ffi.Uint64)>>('photo_asset_clear_geo');
  late final _photo_asset_clear_geo = _photo_asset_clear_geoPtr
      .asFunction<int Function(ffi.Pointer<photo_engine_t>, int)>();
}

final class photo_engine extends ffi.Opaque {}

/// ------------------------------------------------------------------------- */
/// /* Enumerations                                                              */
/// /* -------------------------------------------------------------------------
abstract class photo_status_t {
  static const int PHOTO_STATUS_OK = 0;
  static const int PHOTO_STATUS_INVALID_ARG = 1;
  static const int PHOTO_STATUS_NOT_FOUND = 2;
  static const int PHOTO_STATUS_IO_ERROR = 3;
  static const int PHOTO_STATUS_DECODE_ERROR = 4;
  static const int PHOTO_STATUS_OUT_OF_MEMORY = 5;
  static const int PHOTO_STATUS_CANCELLED = 6;
  static const int PHOTO_STATUS_UNSUPPORTED = 7;
  static const int PHOTO_STATUS_BUSY = 8;
  static const int PHOTO_STATUS_INTERNAL = 9;
  static const int PHOTO_STATUS_BAD_STATE = 10;
}

abstract class photo_stage_t {
  static const int PHOTO_STAGE_PLACEHOLDER32 = 1;
  static const int PHOTO_STAGE_THUMB256 = 2;
  static const int PHOTO_STAGE_FULL = 3;
}

abstract class photo_priority_t {
  /// on-screen, must satisfy in this frame
  static const int PHOTO_PRIORITY_INTERACTIVE = 0;

  /// in current viewport / short prefetch
  static const int PHOTO_PRIORITY_VIEWPORT = 1;

  /// background; pre-cache and recache
  static const int PHOTO_PRIORITY_IDLE = 2;
}

abstract class photo_event_kind_t {
  static const int PHOTO_EVT_STAGE_READY = 1;
  static const int PHOTO_EVT_STAGE_FAILED = 2;

  /// aux64 = processed, aux64_b = total
  static const int PHOTO_EVT_IMPORT_PROGRESS = 3;

  /// Terminal import/rescan event. Carries the incremental-rescan summary:
  /// aux64        = added   (new assets inserted)
  /// aux64_b      = updated (existing assets whose file changed)
  /// _reserved[0] = skipped (unchanged files — size+mtime matched, not re-read)
  /// _reserved[1] = removed (rescan-pruned assets whose file is gone)
  static const int PHOTO_EVT_IMPORT_COMPLETE = 4;
  static const int PHOTO_EVT_SCAN_PROGRESS = 5;
  static const int PHOTO_EVT_CLUSTER_UPDATED = 6;

  /// 7 reserved — was PROVIDER_PROBED (removed; never emitted)
  static const int PHOTO_EVT_LOG = 8;

  /// Async catalog maintenance (compaction) finished. status is the result.
  static const int PHOTO_EVT_MAINTENANCE_COMPLETE = 9;

  /// One semantic-embedding job finished (Stage 9). asset_id = the asset;
  /// aux64 = 1 (one asset processed); status = per-item result
  /// (OK / UNSUPPORTED=skipped / DECODE_ERROR=failed). The Dart indexing
  /// controller counts these to drive progress, like SCAN_PROGRESS for faces.
  static const int PHOTO_EVT_EMBED_PROGRESS = 10;

  /// Async edit export / layered-save finished. status is the result;
  /// request_id matches the photo_asset_export / photo_asset_save_layered id.
  /// (11, not 10: Stage 9 landed EMBED_PROGRESS=10 on main first.)
  static const int PHOTO_EVT_EXPORT_COMPLETE = 11;
}

abstract class photo_log_level_t {
  static const int PHOTO_LOG_TRACE = 0;
  static const int PHOTO_LOG_DEBUG = 1;
  static const int PHOTO_LOG_INFO = 2;
  static const int PHOTO_LOG_WARN = 3;
  static const int PHOTO_LOG_ERROR = 4;
}

/// Engine configuration. Caller fills this and passes to photo_engine_create.
/// The engine copies what it needs; pointers do not need to outlive the call.
///
/// Zero/NULL fields request engine defaults:
/// memory_budget_bytes = 256 MiB
/// disk_budget_bytes   = 16 GiB
/// decode_threads      = max(2, physical_cores - 1)
/// io_threads          = 4
/// ml_threads          = max(1, physical_cores / 2)
final class photo_config_t extends ffi.Struct {
  /// SQLite DB path; must be on local FS
  external ffi.Pointer<ffi.Char> catalog_path_utf8;

  /// LMDB env directory; will be created
  external ffi.Pointer<ffi.Char> cache_path_utf8;

  /// dir for ML models (M6+); may be NULL
  external ffi.Pointer<ffi.Char> models_path_utf8;

  /// memory LRU cap
  @ffi.Uint64()
  external int memory_budget_bytes;

  /// LMDB high-water mark for eviction
  @ffi.Uint64()
  external int disk_budget_bytes;

  @ffi.Uint32()
  external int decode_threads;

  @ffi.Uint32()
  external int io_threads;

  @ffi.Uint32()
  external int ml_threads;

  /// photo_log_level_t
  @ffi.Uint32()
  external int log_level;

  /// reserved; pass 0
  @ffi.Uint32()
  external int flags;
}

/// ------------------------------------------------------------------------- */
/// /* Forward declarations                                                      */
/// /* -------------------------------------------------------------------------
typedef photo_engine_t = photo_engine;

/// Cold path / struct variant. Equivalent to photo_thumb_request_fast but
/// accepts a struct for forward field extension. Cost includes one indirection.
final class photo_thumb_request_t extends ffi.Struct {
  @ffi.Uint64()
  external int asset_id;

  @ffi.Uint64()
  external int slot_id;

  @ffi.Uint64()
  external int generation;

  external ffi.Pointer<ffi.Char> path_utf8;

  @ffi.Uint32()
  external int target_w;

  @ffi.Uint32()
  external int target_h;

  @ffi.Uint32()
  external int wanted_stages_mask;

  @ffi.Uint32()
  external int priority;

  @ffi.Uint32()
  external int flags;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Uint32> _reserved;
}

/// ------------------------------------------------------------------------- */
/// /* Frame acquisition (called by the plugin's texture callback)               */
/// /* -------------------------------------------------------------------------
final class photo_frame_view_t extends ffi.Struct {
  /// device-byte-order BGRA, premultiplied alpha
  external ffi.Pointer<ffi.Uint8> bgra;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  /// bytes per row, >= width * 4
  @ffi.Uint32()
  external int stride;

  /// opaque; pass to photo_slot_release
  external ffi.Pointer<ffi.Void> release_ctx;
}

/// ------------------------------------------------------------------------- */
/// /* Events (pull-based, Dart drains)                                          */
/// /* -------------------------------------------------------------------------
final class photo_event_t extends ffi.Struct {
  /// photo_event_kind_t
  @ffi.Uint32()
  external int kind;

  /// photo_stage_t (where applicable)
  @ffi.Uint32()
  external int stage;

  /// photo_status_t (where applicable)
  @ffi.Int32()
  external int status;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint64()
  external int request_id;

  @ffi.Uint64()
  external int asset_id;

  @ffi.Uint64()
  external int slot_id;

  @ffi.Uint64()
  external int generation;

  /// event-kind dependent payload
  @ffi.Uint64()
  external int aux64;

  @ffi.Uint64()
  external int aux64_b;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint32> _reserved;
}

/// One catalog asset row, for hydrating the Dart library after import. The
/// engine-assigned asset_id is stable across runs (unlike a path hash), so face
/// data and the thumbnail cache stay valid across restarts. `path` is a
/// NUL-terminated absolute path; the buffer holds a full Linux PATH_MAX (4096).
final class photo_asset_t extends ffi.Struct {
  @ffi.Uint64()
  external int asset_id;

  /// bytes
  @ffi.Uint64()
  external int size;

  /// last-modified, ns since epoch
  @ffi.Uint64()
  external int mtime_ns;

  /// 0 until a metadata/codec pass fills it
  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  /// EXIF orientation 1..8
  @ffi.Uint32()
  external int orientation;

  /// 0/1
  @ffi.Int32()
  external int starred;

  /// 0..5
  @ffi.Int32()
  external int rating;

  /// bit0: hidden; bit1: video (§11)
  @ffi.Uint32()
  external int flags;

  /// _reserved[0] = video duration in ms (0 for photos, §11); [1..2] unused
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Uint32> _reserved;

  @ffi.Array.multi([4096])
  external ffi.Array<ffi.Char> path;
}

/// EXIF metadata for an asset, extracted on import and stored in the catalog.
/// Strings are libexif-formatted (e.g. aperture "f/2.8"); empty if absent.
final class photo_metadata_t extends ffi.Struct {
  @ffi.Uint64()
  external int asset_id;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  /// 1..8
  @ffi.Int32()
  external int orientation;

  @ffi.Int32()
  external int iso;

  /// DateTimeOriginal, unix seconds; 0 if absent
  @ffi.Int64()
  external int datetime_unix;

  /// 0/1
  @ffi.Int32()
  external int has_gps;

  @ffi.Int32()
  external int _pad;

  @ffi.Double()
  external double gps_lat;

  @ffi.Double()
  external double gps_lon;

  /// "Make Model"
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> camera;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> lens;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> aperture;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> shutter;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> focal;
}

/// A geotagged asset: its id and decimal-degree coordinates.
final class photo_geopoint_t extends ffi.Struct {
  @ffi.Uint64()
  external int asset_id;

  @ffi.Double()
  external double lat;

  @ffi.Double()
  external double lon;
}

/// ------------------------------------------------------------------------- */
/// /* Albums — user-created collections.                                        */
/// /* -------------------------------------------------------------------------
final class photo_album_t extends ffi.Struct {
  @ffi.Uint64()
  external int album_id;

  /// 0 if unset / empty
  @ffi.Uint64()
  external int cover_asset_id;

  /// member count
  @ffi.Int32()
  external int count;

  @ffi.Int32()
  external int _pad;

  /// ns since epoch
  @ffi.Int64()
  external int created;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> name;
}

/// ------------------------------------------------------------------------- */
/// /* Maintenance — compaction, stats, checkpoint.                               */
/// /* -------------------------------------------------------------------------
final class photo_catalog_stats_t extends ffi.Struct {
  /// pages currently in the DB file
  @ffi.Int64()
  external int page_count;

  /// unused pages reclaimable by VACUUM
  @ffi.Int64()
  external int freelist_count;

  /// bytes per page (DB size ≈ page_count*size)
  @ffi.Int64()
  external int page_size;
}

/// Star / rating / caption for one asset.
final class photo_organize_t extends ffi.Struct {
  /// 0/1
  @ffi.Int32()
  external int starred;

  /// 0..5
  @ffi.Int32()
  external int rating;

  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> caption;
}

/// Output options for photo_asset_export2. Zero-init for the legacy behaviour
/// (original size, quality 92 via the <=0 fallback, no watermark). The
/// watermark applies when `wm_text` is non-empty; it is drawn AFTER the resize
/// so `wm_size` / `wm_margin` (fractions of the OUTPUT short edge) are exact in
/// the written file. It never enters the edit-spec `text=` grammar (positional,
/// free-text-last — it cannot carry opacity compatibly).
final class photo_export_options_t extends ffi.Struct {
  /// long-edge px bound; 0 = original size
  @ffi.Uint32()
  external int max_dim;

  /// jpg 1..100; <=0 -> 92
  @ffi.Int32()
  external int quality;

  /// watermark colour+opacity, 0xAARRGGBB
  @ffi.Uint32()
  external int wm_argb;

  /// text height / short edge; <=0 -> 0.04
  @ffi.Float()
  external double wm_size;

  /// corner inset / short edge; <0 -> 0.02
  @ffi.Float()
  external double wm_margin;

  /// PHOTO_EXPORT_ANCHOR_*
  @ffi.Uint32()
  external int wm_anchor;

  /// reserved; pass 0
  @ffi.Uint32()
  external int flags;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint32> _reserved;

  /// UTF-8, NUL-terminated; empty = no watermark
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> wm_text;
}

/// §11/collage: one cell — a normalized rect on the canvas [0,1] plus the source
/// to render into it. `spec_utf8` may be NULL/"" (no edit). Pointers are only
/// borrowed for the duration of the photo_create_collage call.
final class photo_collage_cell_t extends ffi.Struct {
  /// fractions of the canvas
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double w;

  @ffi.Float()
  external double h;

  /// source image path
  external ffi.Pointer<ffi.Char> src_utf8;

  /// edit spec ("" / NULL = none)
  external ffi.Pointer<ffi.Char> spec_utf8;
}

/// A red-eye brush region: normalized centre + radius as a fraction of the image
/// short edge (matches the `redeye=x,y,r` edit-spec grammar).
final class photo_region_t extends ffi.Struct {
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double r;
}

/// A person = a confirmed/named cluster. `name` is NUL-terminated UTF-8.
final class photo_person_t extends ffi.Struct {
  @ffi.Uint64()
  external int person_id;

  /// representative cluster, -1 if none
  @ffi.Int64()
  external int cluster_id;

  /// best face for the avatar (highest quality)
  @ffi.Uint64()
  external int cover_face_id;

  @ffi.Int32()
  external int face_count;

  @ffi.Int32()
  external int confirmed_count;

  /// 0/1
  @ffi.Int32()
  external int confirmed;

  @ffi.Int32()
  external int _pad;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> name;
}

/// One face row: detection metadata + cluster/person links.
final class photo_face_t extends ffi.Struct {
  @ffi.Uint64()
  external int face_id;

  @ffi.Uint64()
  external int asset_id;

  /// -1 = unassigned
  @ffi.Int64()
  external int cluster_id;

  /// -1 = unconfirmed
  @ffi.Int64()
  external int person_id;

  /// source-image pixels
  @ffi.Float()
  external double box_x;

  @ffi.Float()
  external double box_y;

  @ffi.Float()
  external double box_w;

  @ffi.Float()
  external double box_h;

  @ffi.Float()
  external double det_score;

  @ffi.Float()
  external double quality;

  /// 0 = suggestion, 1 = user-confirmed
  @ffi.Int32()
  external int confirmed;

  /// 0/1 — user hid this detection
  @ffi.Int32()
  external int ignored;

  /// 0/1 — user-drawn rectangle (no embedding)
  @ffi.Int32()
  external int manual;

  @ffi.Int32()
  external int _pad;
}

/// Embedding progress counts for the indexing UI. `total` is all non-hidden
/// assets; `pending` includes assets with no row yet.
final class photo_embed_counts_t extends ffi.Struct {
  @ffi.Int64()
  external int done;

  @ffi.Int64()
  external int pending;

  @ffi.Int64()
  external int processing;

  @ffi.Int64()
  external int failed;

  @ffi.Int64()
  external int skipped;

  @ffi.Int64()
  external int total;
}

/// (asset_id, dominant colour 0xRRGGBB) for every embedded asset — drives colour
/// search. Fills up to `cap`, returns the TOTAL available (grow + re-call).
final class photo_asset_color_t extends ffi.Struct {
  @ffi.Uint64()
  external int asset_id;

  /// 0xRRGGBB
  @ffi.Int32()
  external int rgb;

  @ffi.Int32()
  external int _pad;
}

/// One ranked search result.
final class photo_search_hit_t extends ffi.Struct {
  @ffi.Uint64()
  external int asset_id;

  /// cosine similarity in [-1, 1]
  @ffi.Float()
  external double score;

  @ffi.Float()
  external double _pad;
}

/// Saved searches (saved_search table). query_json is opaque UTF-8.
final class photo_saved_search_t extends ffi.Struct {
  @ffi.Uint64()
  external int id;

  /// ns since epoch
  @ffi.Int64()
  external int created;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> name;
}

const int PHOTO_EXPORT_ANCHOR_BR = 0;

const int PHOTO_EXPORT_ANCHOR_BL = 1;

const int PHOTO_EXPORT_ANCHOR_TR = 2;

const int PHOTO_EXPORT_ANCHOR_TL = 3;

const int PHOTO_EXPORT_ANCHOR_CENTER = 4;

const int PHOTO_ABI_VERSION = 1;

const int PHOTO_VERSION_MAJOR = 0;

const int PHOTO_VERSION_MINOR = 1;

const int PHOTO_VERSION_PATCH = 0;

const int PHOTO_STAGE_MASK_PLACEHOLDER32 = 1;

const int PHOTO_STAGE_MASK_THUMB256 = 2;

const int PHOTO_STAGE_MASK_FULL = 4;

const int PHOTO_STAGE_MASK_DEFAULT = 3;

const int PHOTO_ASSET_FLAG_HIDDEN = 1;

const int PHOTO_ASSET_FLAG_VIDEO = 2;

const int PHOTO_SEMANTIC_RELEASE_IMAGE = 1;

const int PHOTO_SEMANTIC_RELEASE_TEXT = 2;
